import { StyleSheet } from "react-native";

export const createFormularioStyles = (colors: any) =>
  StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: "#282A30",
    },
    container: {
      flex: 1,
      paddingHorizontal: 24,
      justifyContent: "space-between",
      paddingBottom: 40,
    },
    logoContainer: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      marginTop: 45,
      marginBottom: 12,
    },
    logoText: {
      fontSize: 36,
      fontFamily: "Poppins_700Bold_Italic",
      color: "#C8C9D2",
      marginLeft: 8,
      letterSpacing: -0.5,
      paddingTop: 5,
    },
    progressContainer: {
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 40,
      paddingHorizontal: 20,
    },
    progressStep: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: "#2A2A2A",
      borderWidth: 2,
      borderColor: "#404040",
      justifyContent: "center",
      alignItems: "center",
      marginHorizontal: 4,
    },
    progressStepActive: {
      backgroundColor: "#4CAF50",
      borderColor: "#4CAF50",
    },
    progressStepCompleted: {
      backgroundColor: "#4CAF50",
      borderColor: "#4CAF50",
    },
    progressStepText: {
      fontSize: 14,
      fontWeight: "600",
      color: "#888",
    },
    progressStepTextActive: {
      color: "#FFFFFF",
    },
    progressLine: {
      flex: 1,
      height: 2,
      backgroundColor: "#404040",
      marginHorizontal: 8,
    },
    progressLineCompleted: {
      backgroundColor: "#4CAF50",
    },
    contentContainer: {
      flex: 1,
      justifyContent: "center",
      paddingVertical: 20,
    },
    title: {
      fontSize: 16,
      fontWeight: "500",
      color: "#888",
      textAlign: "center",
      marginBottom: 40,
      letterSpacing: 0.5,
    },
    sectionTitle: {
      fontSize: 24,
      fontFamily: "Poppins_700Bold",
      color: "#C8C9D2",
      marginBottom: 16,
      letterSpacing: -0.5,
    },
    label: {
      fontSize: 18,
      fontFamily: "Poppins_400Regular",
      color: "#C8C9D2",
      marginBottom: 6,
      lineHeight: 24,
    },
    introText: {
      fontSize: 20,
      fontFamily: "Poppins_400Regular",
      color: "#C8C9D2",
      marginBottom: 20,
      lineHeight: 24,
    },
    input: {
      backgroundColor: "transparent",
      borderRadius: 0,
      borderWidth: 0,
      borderBottomWidth: 3,
      borderColor: "#C8C9D2",
      paddingHorizontal: 0,
      paddingVertical: 12,
      fontSize: 16,
      color: "#C8C9D2",
      marginBottom: 24,
      fontWeight: "500",
    },
    inputFocused: {
      borderColor: "#4CAF50",
      borderWidth: 2,
    },
    inputGroup: {
      marginBottom: 24,
    },
    inputPlaceholder: {
      color: "#53545D",
    },
    radioContainer: {
      marginBottom: 24,
    },
    radioOption: {
      flexDirection: "row",
      alignItems: "center",
      marginVertical: 4,
      paddingHorizontal: 0,
      marginBottom: 8,
    },
    checkboxOption: {
      flexDirection: "row",
      alignItems: "center",
      marginVertical: 4,
      paddingHorizontal: 0,
      marginBottom: 8,

    },
    radioCircle: {
      width: 20,
      height: 20,
      borderRadius: 10,
      borderWidth: 2,
      borderColor: "#404040",
      marginRight: 12,
      justifyContent: "center",
      alignItems: "center",
    },
    radioCircleSelected: {
      borderColor: "#4CAF50",
    },
    radioInner: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: "#4CAF50",
    },
    radioText: {
      fontSize: 16,
      color: "#C8C9D2",
      fontWeight: "700",
    },
    radioLabel: {
      fontSize: 18,
      fontFamily: "Poppins_400Regular",
      color: "#FFFFFF",
      flex: 1,
      paddingLeft: 6,
    },
    checkboxLabel: {
      fontSize: 18,
      fontFamily: "Poppins_400Regular",
      color: "#FFFFFF",
      flex: 1,
      paddingLeft: 6,
    },
    button: {
      backgroundColor: "#D9D9D9",
      fontFamily: "Poppins_400Regular",
      borderRadius: 12,
      paddingVertical: 16,
      paddingHorizontal: 32,
      alignItems: "center",
      justifyContent: "center",
      marginTop: "auto",
      shadowColor: "#4CAF50",
      shadowOffset: {
        width: 0,
        height: 4,
      },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 8,
    },
    buttonDisabled: {
      backgroundColor: "#2A2A2A",
      shadowOpacity: 0,
      elevation: 0,
    },
    buttonText: {
      fontFamily: "Poppins_400Regular",
      fontSize: 18,
      fontWeight: "600",
      color: "#000000",
      letterSpacing: 0.5,
    },
    buttonTextDisabled: {
      color: "#888",
    },
    backButton: {
      position: "absolute",
      top: 60,
      left: 24,
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: "#2A2A2A",
      justifyContent: "center",
      alignItems: "center",
      zIndex: 1,
    },
    skipButton: {
      position: "absolute",
      top: 60,
      right: 24,
      paddingHorizontal: 16,
      paddingVertical: 8,
      zIndex: 1,
    },
    skipButtonText: {
      fontSize: 16,
      color: "#888",
      fontWeight: "500",
    },
    formGroup: {
      marginBottom: 24,
    },
    inlineInputs: {
      flexDirection: "row",
      justifyContent: "space-between",
      gap: 12,
    },
    inlineInput: {
      flex: 1,
    },
    errorText: {
      fontSize: 14,
      color: "#FF5252",
      marginTop: -16,
      marginBottom: 16,
      marginLeft: 4,
    },
    helperText: {
      fontSize: 14,
      color: "#888",
      marginTop: -16,
      marginBottom: 16,
      marginLeft: 4,
      lineHeight: 18,
    },
  });
