import { Dimensions, StyleSheet } from "react-native";
const { width } = Dimensions.get("window");

export const createGeralStyles = (colors: any) =>
  StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: "#282A30",
    },
    container: {
      flex: 1,
      paddingHorizontal: 24,
      justifyContent: "space-between",
      paddingBottom: 40,
    },
    logoContainer: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      marginTop: 45,
      marginBottom: 12,
    },
    formContainer: {
      justifyContent: "center",
      flex: 1,
      paddingHorizontal: 24,
      paddingBottom: 40,
    },
    homeContainer: {
      flex: 1,
      justifyContent: "space-between",
      paddingBottom: 40,
    },
    headerChat: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      marginTop: 50,
      marginBottom: 12,
    },
    chatContainer: {
      flex: 1,
      paddingHorizontal: 24,
      justifyContent: "space-between",
    },
    logoText: {
      fontSize: 36,
      fontFamily: "Poppins_700Bold_Italic",
      color: "#C8C9D2",
      marginLeft: 8,
      letterSpacing: -0.5,
      paddingTop: 5,
    },
    progressContainer: {
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 40,
      paddingHorizontal: 20,
    },
    progressStep: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: "#2A2A2A",
      borderWidth: 2,
      borderColor: "#404040",
      justifyContent: "center",
      alignItems: "center",
      marginHorizontal: 4,
    },
    progressStepActive: {
      backgroundColor: "#4CAF50",
      borderColor: "#4CAF50",
    },
    progressStepCompleted: {
      backgroundColor: "#4CAF50",
      borderColor: "#4CAF50",
    },
    progressStepText: {
      fontSize: 14,
      fontWeight: "600",
      color: "#888",
    },
    progressStepTextActive: {
      color: "#FFFFFF",
    },
    progressLine: {
      flex: 1,
      height: 2,
      backgroundColor: "#404040",
      marginHorizontal: 8,
    },
    progressLineCompleted: {
      backgroundColor: "#4CAF50",
    },
    contentContainer: {
      flex: 1,
      justifyContent: "center",
      paddingVertical: 20,
    },
    title: {
      fontSize: 16,
      fontWeight: "500",
      color: "#888",
      textAlign: "center",
      marginBottom: 40,
      letterSpacing: 0.5,
    },
    sectionTitle: {
      textAlign: "center",
      fontSize: 24,
      fontFamily: "Poppins_700Bold",
      color: "#C8C9D2",
      marginBottom: 16,
      letterSpacing: -0.5,
    },
    label: {
      fontSize: 18,
      fontFamily: "Poppins_400Regular",
      color: "#C8C9D2",
      marginBottom: 6,
      lineHeight: 24,
    },
    introText: {
      fontSize: 20,
      fontFamily: "Poppins_400Regular",
      color: "#C8C9D2",
      marginBottom: 20,
      lineHeight: 24,
    },
    input: {
      fontFamily: "Poppins_400Regular",
      backgroundColor: "transparent",
      borderRadius: 0,
      borderWidth: 0,
      borderBottomWidth: 3,
      borderColor: "#C8C9D2",
      paddingHorizontal: 0,
      paddingVertical: 12,
      fontSize: 16,
      color: "#C8C9D2",
      marginBottom: 24,
      fontWeight: "500",
    },
    inputFocused: {
      borderColor: "#4CAF50",
      borderWidth: 2,
    },
    inputGroup: {
      marginBottom: 24,
    },
    inputPlaceholder: {
      color: "#53545D",
    },
    radioContainer: {
      marginBottom: 24,
    },
    radioOption: {
      flexDirection: "row",
      alignItems: "center",
      marginVertical: 4,
      paddingHorizontal: 0,
      marginBottom: 8,
    },
    checkboxOption: {
      flexDirection: "row",
      alignItems: "center",
      marginVertical: 4,
      paddingHorizontal: 0,
      marginBottom: 8,
    },
    radioCircle: {
      width: 20,
      height: 20,
      borderRadius: 10,
      borderWidth: 2,
      borderColor: "#404040",
      marginRight: 12,
      justifyContent: "center",
      alignItems: "center",
    },
    radioCircleSelected: {
      borderColor: "#4CAF50",
    },
    radioInner: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: "#4CAF50",
    },
    radioText: {
      fontSize: 16,
      color: "#C8C9D2",
      fontWeight: "700",
    },
    radioLabel: {
      fontSize: 18,
      fontFamily: "Poppins_400Regular",
      color: "#FFFFFF",
      flex: 1,
      paddingLeft: 6,
    },
    checkboxLabel: {
      fontSize: 18,
      fontFamily: "Poppins_400Regular",
      color: "#FFFFFF",
      flex: 1,
      paddingLeft: 6,
    },
    button: {
      backgroundColor: "#D9D9D9",
      fontFamily: "Poppins_500Medium",
      borderRadius: 12,
      paddingVertical: 16,
      paddingHorizontal: 32,
      alignItems: "center",
      justifyContent: "center",
      marginTop: "auto",
      elevation: 8,
    },
    buttonOutline: {
      fontFamily: "Poppins_500Medium",
      borderRadius: 12,
      paddingVertical: 16,
      paddingHorizontal: 32,
      alignItems: "center",
      justifyContent: "center",
      marginTop: 18,
      borderWidth: 1,
      borderColor: "#D9D9D9",
    },
    buttonDisabled: {
      backgroundColor: "#2A2A2A",
      shadowOpacity: 0,
      elevation: 0,
    },
    buttonText: {
      fontFamily: "Poppins_500Medium",
      fontSize: 14,
      fontWeight: "600",
      color: "#000000",
      letterSpacing: 0.5,
    },
    buttonTextOutline: {
      fontFamily: "Poppins_500Medium",
      fontSize: 14,
      fontWeight: "600",
      color: "#D9D9D9",
      letterSpacing: 0.5,
    },
    buttonTextDisabled: {
      color: "#888",
    },
    googleButton: {
      backgroundColor: "#D9D9D9",
      fontFamily: "Poppins_500Medium",
      borderRadius: 12,
      paddingVertical: 16,
      paddingHorizontal: 10,
      alignItems: "center",
      justifyContent: "center",
      marginTop: 15,
      elevation: 8,
      display: "flex",
      flexDirection: "row",
      gap: 8,
      alignContent: "center",
    },
    googleButtonText: {
      fontFamily: "Poppins_500Medium",
      fontSize: 18,
      fontWeight: "600",
      color: "#000000",
      letterSpacing: 0.5,
    },
    backButton: {
      position: "absolute",
      top: 60,
      left: 24,
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: "#2A2A2A",
      justifyContent: "center",
      alignItems: "center",
      zIndex: 1,
    },
    skipButton: {
      position: "absolute",
      top: 60,
      right: 24,
      paddingHorizontal: 16,
      paddingVertical: 8,
      zIndex: 1,
    },
    skipButtonText: {
      fontSize: 14,
      color: "#888",
      fontWeight: "500",
    },
    formGroup: {
      marginBottom: 24,
    },
    inlineInputs: {
      flexDirection: "row",
      justifyContent: "space-between",
      gap: 12,
    },
    inlineInput: {
      flex: 1,
    },
    errorText: {
      fontSize: 14,
      color: "#FF5252",
      marginTop: -16,
      marginBottom: 16,
      marginLeft: 4,
    },
    helperText: {
      fontSize: 14,
      color: "#888",
      marginTop: -16,
      marginBottom: 16,
      marginLeft: 4,
      lineHeight: 18,
    },
    linkContainer: {
      marginTop: 20,
      alignItems: "center",
    },
    linkText: {
      fontSize: 18,
      fontFamily: "Poppins_400Regular",
      color: "#C8C9D2",
      marginBottom: 6,
      lineHeight: 24,
      textAlign: "center",
    },
    link: {
      fontSize: 18,
      fontFamily: "Poppins_400Regular",
      color: "#C8C9D2",
      marginBottom: 6,
      lineHeight: 24,
      textDecorationLine: "underline",
    },
    // Home
    horizontalScrollView: {
      width: width,
    },
    chartPage: {
      width: width,
      justifyContent: "center",
      alignItems: "center",
    },
    pagination: {
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      marginTop: 10,
    },
    dot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      marginHorizontal: 4,
    },
    divider: {
      height: 1,
      backgroundColor: "#e0e0e0",
      marginHorizontal: 20,
      marginVertical: 15,
    },
    tipsContainer: {
      paddingHorizontal: 20,
      marginTop: 10,
      marginBottom: 20,
    },
    tipsTitle: {
      fontSize: 20,
      fontWeight: "bold",
      marginBottom: 10,
      textAlign: "center",
    },
    card: {
      justifyContent: "center",
      alignItems: "center",
      padding: 20,
      borderRadius: 15,
      minHeight: 120,
      backgroundColor: "#53545D",
      color: "#FFFFFF",
    },
    tipText: {
      fontSize: 16,
      color: "#C8C9D2",
      textAlign: "center",
      fontStyle: "italic",
    },
    addButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "#D9D9D9",
      elevation: 8,
    },
    header: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      width: "100%",
      paddingHorizontal: 15,
    },
    calorieContainer: {
      padding: 10,
      alignItems: "center",
    },
    chartContainer: {
      marginTop: 20,
    },
    messageText: {
      fontSize: 16,
      textAlign: "center",
      paddingVertical: 40,
    },
    noDataText: {
      textAlign: "center",
      marginTop: 30,
      fontSize: 16,
      paddingVertical: 40,
      fontFamily: "Poppins_400Regular",
      color: "#C8C9D2",
    },
    modalOverlay: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "rgba(0,0,0,0.5)",
    },
    modalTitle: {
      fontSize: 20,
      marginBottom: 15,
    },
    modalButtons: {
      flexDirection: "row",
      justifyContent: "space-between",
      width: "100%",
      marginTop: 20,
      gap: 10,
    },
    tooltip: {
      backgroundColor: "rgba(0,0,0,0.8)",
      padding: 8,
      borderRadius: 6,
    },
    overlay: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "rgba(0,0,0,0.6)",
    },
    modalView: {
      width: "90%",
      borderRadius: 20,
      padding: 25,
      elevation: 5,
      backgroundColor: "#282A30",
    },
    mealTypeContainer: {
      fontFamily: "Poppins_400Regular",
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "center",
      marginBottom: 5,
    },
    mealTypeButton: {
      fontFamily: "Poppins_400Regular",
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderWidth: 1,
      borderRadius: 20,
      margin: 4,
    },
    estimateButton: {
      width: "100%",
      padding: 15,
      borderRadius: 10,
      alignItems: "center",
      marginTop: 15,
    },
    saveButton: {
      width: "100%",
      padding: 15,
      borderRadius: 10,
      alignItems: "center",
      marginTop: 10,
    },
    saveButtonText: {
      fontFamily: "Poppins_500Medium",
      fontSize: 14,
      fontWeight: "600",
      color: "#000000",
      letterSpacing: 0.5,
    },
    mealCard: {
      backgroundColor: "#53545D",
      // backgroundColor: "#ffffff",
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      padding: 16,
      borderRadius: 12,
      marginBottom: 12,
    },
    mealInfo: {
      flex: 1,
      marginRight: 8,
    },
    mealActions: {
      flexDirection: "row",
      alignItems: "center",
    },
    mealType: {
      fontFamily: "Poppins_600SemiBold",
      color: "#FFFFFF",
      fontSize: 16,
    },
    mealDescription: {
      fontFamily: "Poppins_400Regular",
      color: "#C8C9D2",
      fontSize: 14,
      marginTop: 4,
    },
    mealCalories: {
      fontSize: 16,
      fontWeight: "bold",
    },
    emptyText: {
      textAlign: "center",
      marginTop: 50,
      fontSize: 16,
    },

    // Favorites
    searchContainer: {
      flexDirection: "row",
      alignItems: "center",
      marginTop: 20,
      marginBottom: 16,
      marginVertical: 8,
    },
    searchBox: {
      backgroundColor: "#41424A",
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 12,
      borderRadius: 45,
      height: 60,
      marginRight: 8,
    },
    searchInput: {
      fontFamily: "Poppins_400Regular",
      backgroundColor: "#41424A",
      color: "#C8C9D2",
      flex: 1,
      fontSize: 16,
      marginLeft: 8,
      paddingVertical: 0,
      marginBottom: 0,
    },
    addFolderButton: {
      width: 60,
      height: 60,
      borderRadius: "50%",
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "#41424A",
      elevation: 8,
    },
    newFolderContainer: {
      width: "100%",
      borderRadius: 20,
      padding: 25,
      elevation: 5,
      backgroundColor: "#282A30",
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 12,
    },
    newFolderInput: {
      fontFamily: "Poppins_400Regular",
      backgroundColor: "transparent",
      borderRadius: 0,
      borderWidth: 0,
      borderBottomWidth: 3,
      borderColor: "#C8C9D2",
      paddingHorizontal: 0,
      paddingVertical: 12,
      fontSize: 16,
      color: "#C8C9D2",
      marginBottom: 24,
      width: "60%",
      marginHorizontal: 10,
    },
    iconButton: {
      marginLeft: 8,
    },
    grid: {
      paddingBottom: 16,
    },
    folderCard: {
      flex: 1,
      margin: 8,
      padding: 16,
      borderRadius: 35,
      position: "relative",
      minWidth: 140,
      maxWidth: "48%",
      aspectRatio: 1,
      backgroundColor: "#41424A",
      flexDirection: "column",
      justifyContent: "center",
      alignItems: "center",
    },
    menuButton: {
      position: "absolute",
      top: 18,
      right: 10,
    },
    menuOptions: {
      position: "absolute",
      top: 40,
      right: 8,
      backgroundColor: "#282A30",
      borderRadius: 8,
      elevation: 5,
      padding: 6,
      zIndex: 100,
    },
    menuItem: {
      padding: 6,
      fontSize: 14,
    },
    loadingContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
    },
    folderHeader: {
      flexDirection: "row",
      // justifyContent: "center",
      alignItems: "center",
      paddingHorizontal: 16,
      paddingVertical: 12,
    },
    recipeBackButton: {
      marginRight: 12,
      color: "#C8C9D2",
    },
    inputContainer: {
      marginHorizontal: 16,
      marginBottom: 12,
      borderRadius: 8,
      borderWidth: 1,
      padding: 12,
    },
    error: {
      color: "red",
      marginTop: 6,
    },
    buttonsRow: {
      flexDirection: "column",
      justifyContent: "space-between",
      marginTop: 12,
      gap: 10,
    },
    recipeCard: {
      marginHorizontal: 16,
      marginVertical: 6,
      padding: 16,
      borderRadius: 8,
      position: "relative",
      elevation: 2,
      backgroundColor: "#53545D",
    },
    recipeText: {
      fontFamily: "Poppins_400Regular",
      fontSize: 14,
    },
    deleteButton: {
      position: "absolute",
      right: 8,
      top: 8,
      padding: 4,
      zIndex: 1,
    },
    floatingButton: {
      position: "absolute",
      right: 20,
      bottom: 30,
      width: 56,
      height: 56,
      borderRadius: 28,
      justifyContent: "center",
      alignItems: "center",
      shadowColor: "#000",
      shadowOpacity: 0.3,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 4 },
      elevation: 5,
      backgroundColor: "#D9D9D9",
    },

    // Profile
    profileContainer: {
      flex: 1,
      paddingTop: 20,
      paddingHorizontal: 24,
      paddingBottom: 40,
    },
    settingsButton: {
      position: "absolute",
      top: 60,
      right: 20,
      zIndex: 1,
    },
    profileSection: {
      marginTop: 30,
    },
    avatarContainer: {
      marginTop: 50,
      alignItems: "center",
      width: "100%",
    },
    avatar: {
      width: 120,
      height: 120,
      borderRadius: 40,
      // borderWidth: 2,
    },
    userName: {
      fontFamily: "Poppins_600SemiBold",
      color: "#C8C9D2",
      fontSize: 24,
      fontWeight: "600",
      marginTop: 12,
    },

    // Chat
    chat: {
      padding: 16,
      flexGrow: 1,
      justifyContent: "flex-end",
    },
    buttonNewChat: {
      backgroundColor: "#D9D9D9",
      fontFamily: "Poppins_500Medium",
      borderRadius: 12,
      paddingVertical: 16,
      paddingHorizontal: 32,
      alignItems: "center",
      justifyContent: "center",
      marginTop: "auto",
      elevation: 8,
      padding: 12,
      marginHorizontal: 16,
      marginBottom: 10,
    },
    buttonTextNewChat: {
      fontFamily: "Poppins_500Medium",
      fontSize: 14,
      fontWeight: "600",
      color: "#000000",
      letterSpacing: 0.5,
    },
    message: {
      padding: 10,
      borderRadius: 20,
      marginBottom: 10,
      maxWidth: "80%",
    },
    inputWrapper: {
      flexDirection: "row",
      alignItems: "center",
      borderRadius: 12,
      borderWidth: 1,
      marginHorizontal: 16,
      marginBottom: 136,
      paddingHorizontal: 12,
      height: 60,
      borderColor: "#D9D9D9",
    },
    sendInlineButton: {
      marginLeft: 8,
      backgroundColor: "#D9D9D9",
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 12,
    },

    profileImageContainer: {
  alignItems: 'center',
  marginBottom: 20,
},
profileImage: {
  width: 120,
  height: 120,
  borderRadius: 60,
  backgroundColor: colors.iconInactive, // Cor de fundo enquanto carrega
},
changeImageText: {
  color: colors.primary,
  marginTop: 10,
  fontSize: 16,
  },

  
  });
